library(fields)
library(fitdc)
library(gdata)
library(geonames)
library(ggmap)
library(ggplot2)
library(gridExtra)
library(htmltools)
library(htmlwidgets)
library(leaflet)
library(lubridate)
library(plotly)
  library(plyr) ### Must be run before dplyr
  library(dplyr) ### Must be run after plyr
library(rgdal)
library(rmarkdown)
library(scales)
library(shiny)
library(sp)
library(XML)